--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CraftCamp1/EasyRandomTeleporter
build-by-default: true
branches:
- main
projects:
  EasyRandomTeleporter:
    path: ""
    icon: "icon.png"
...
